### ISSUE TITLE
Cannot run the shortcuts in a previously resized window.

### ISSUE THREAD

**Issue by jvpessoa10** [shiznatix/bifocals-gnome-extension#4]
**Steps to reproduce:**
1. Resize some window with regular shortcut (e.g Super + Left).
2. Try to use the extension's shortcuts (e.g Super + Alt + Left).

**Expected Behavior:**
The window should resize properly.

**Actual behavior:**
Nothing happens.

**Comment by shiznatix** [comment]
This seems to be due to the window being "snapped" and resizing is disabled in that window state.

**Comment by shiznatix** [comment]
Actually, I was very wrong, and I found the fix and have put the fix in the latest version. Just update your version to latest and you should be good!
